[book]
title = "GSuite - Toolbox"
authors = ["Daniele - @DaniFluffyCat"]
description = "Toolbox com fórmulas customizadas e miniscripts úteis na GSuite e Apps Script"
language = "pt"
multilingual = false
src = "src"
