[book]
title = "Toolbox - DaniFluffyCat"
authors = ["Daniele - @DaniFluffyCat"]
description = "Ambiente para publicar miniscripts, fórmulas de Excel e GSheets úteis, ou qualquer outro snippet útil"
language = "pt"
multilingual = false
src = "src"

[build]
create-missing = false 
